/**
 * GENERATED FILE. Do not edit by hand.
 *
 * TypeScript types for the API (Song, Line, AttemptResult and so on), produced by
 * scripts/gen-types.sh from the backend's OpenAPI output.
 *
 * Owner: A. Spec: docs/contracts/api.md.
 */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/songs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Songs */
        get: operations["list_songs_api_v1_songs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/songs/{song_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Song */
        get: operations["get_song_api_v1_songs__song_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Attempt */
        post: operations["create_attempt_api_v1_attempts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AttemptResult */
        AttemptResult: {
            /** Attempt Id */
            attempt_id: string;
            /** Song Id */
            song_id: string;
            /** Line Index */
            line_index: number;
            /** Word Index */
            word_index: number | null;
            /**
             * Target
             * @enum {string}
             */
            target: "line" | "word";
            /** Mode */
            mode: ("spoken" | "singing") | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "no_speech";
            /** Engine */
            engine: string;
            scores: components["schemas"]["Scores"];
            /** Words */
            words: components["schemas"]["WordResult"][];
            /** Syllables */
            syllables: components["schemas"]["SyllableResult"][];
            heard: components["schemas"]["Heard"] | null;
            /** Next Step */
            next_step: components["schemas"]["PracticeWordStep"] | components["schemas"]["LineStep"];
        };
        /** Body_create_attempt_api_v1_attempts_post */
        Body_create_attempt_api_v1_attempts_post: {
            /** Audio */
            audio: string;
            /** Song Id */
            song_id: string;
            /** Line Index */
            line_index: number;
            /**
             * Target
             * @enum {string}
             */
            target: "line" | "word";
            /**
             * Mode
             * @description 'spoken' or 'singing'; required for line, ignored for word
             */
            mode?: string | null;
            /** Word Index */
            word_index?: number | null;
        };
        /** ErrorBody */
        ErrorBody: {
            error: components["schemas"]["ErrorDetail"];
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** Feedback */
        Feedback: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** Health */
        Health: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /**
             * Grader
             * @enum {string}
             */
            grader: "mock" | "real";
        };
        /** Heard */
        Heard: {
            /** Hanzi */
            hanzi: string;
            /** Pinyin */
            pinyin: string;
        };
        /** Line */
        Line: {
            /** Index */
            index: number;
            /** Start Ms */
            start_ms: number;
            /** End Ms */
            end_ms: number;
            /** Text */
            text: string;
            /** Translation */
            translation: string | null;
            /** Syllables */
            syllables: components["schemas"]["LyricSyllable"][];
            /** Words */
            words: components["schemas"]["Word"][];
        };
        /** LineStep */
        LineStep: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "next_line" | "retry_line";
            /** Message */
            message: string;
        };
        /** LyricSyllable */
        LyricSyllable: {
            /** Hanzi */
            hanzi: string;
            /** Pinyin */
            pinyin: string;
            /** Pinyin Numeric */
            pinyin_numeric: string;
            /** Initial */
            initial: string;
            /** Final */
            final: string;
            /** Tone */
            tone: number;
            /** Start Ms */
            start_ms: number | null;
            /** End Ms */
            end_ms: number | null;
            /** Index */
            index: number;
            /** Word Index */
            word_index: number;
        };
        /** Part */
        Part: {
            /** Expected */
            expected: string;
            /** Heard */
            heard: string | null;
            /** Score */
            score: number | null;
        };
        /** PracticeWordStep */
        PracticeWordStep: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "practice_word";
            /** Word Index */
            word_index: number;
            /** Message */
            message: string;
        };
        /** Scores */
        Scores: {
            /** Overall */
            overall: number | null;
            /** Pronunciation */
            pronunciation: number | null;
            /** Completeness */
            completeness: number | null;
            /** Rhythm */
            rhythm: number | null;
            /** Tone */
            tone: number | null;
            /** Melody */
            melody: number | null;
        };
        /** Song */
        Song: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Artist */
            artist: string;
            /** Line Count */
            line_count: number;
            /** Audio Url */
            audio_url: string;
            /** Lines */
            lines: components["schemas"]["Line"][];
        };
        /** SongSummary */
        SongSummary: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Artist */
            artist: string;
            /** Line Count */
            line_count: number;
        };
        /** SyllableResult */
        SyllableResult: {
            /** Index */
            index: number;
            /** Hanzi */
            hanzi: string;
            /** Pinyin */
            pinyin: string;
            /**
             * Status
             * @enum {string}
             */
            status: "good" | "ok" | "wrong" | "missing";
            /** Score */
            score: number | null;
            initial: components["schemas"]["Part"] | null;
            final: components["schemas"]["Part"] | null;
            tone: components["schemas"]["ToneGrade"] | null;
            timing: components["schemas"]["Timing"] | null;
            feedback: components["schemas"]["Feedback"] | null;
        };
        /** Timing */
        Timing: {
            /** Start Ms */
            start_ms: number;
            /** End Ms */
            end_ms: number;
            /** Offset Ms */
            offset_ms: number | null;
            /** Score */
            score: number | null;
        };
        /** ToneGrade */
        ToneGrade: {
            /** Expected */
            expected: number;
            /** Heard */
            heard: number | null;
            /** Score */
            score: number | null;
        };
        /** Word */
        Word: {
            /** Index */
            index: number;
            /** Text */
            text: string;
            /** Syllable Indices */
            syllable_indices: number[];
            /** Gloss */
            gloss: string | null;
            /** Audio Url */
            audio_url: string | null;
        };
        /** WordResult */
        WordResult: {
            /** Index */
            index: number;
            /** Text */
            text: string;
            /** Pinyin */
            pinyin: string;
            /**
             * Status
             * @enum {string}
             */
            status: "good" | "ok" | "wrong" | "missing";
            /** Score */
            score: number | null;
            /** Syllable Indices */
            syllable_indices: number[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    list_songs_api_v1_songs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SongSummary"][];
                };
            };
        };
    };
    get_song_api_v1_songs__song_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                song_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Song"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create_attempt_api_v1_attempts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_attempt_api_v1_attempts_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptResult"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}
